.PHONY: clean All

All:
	@echo "----------Building project:[ rainflow_algorithm_v_0_2 - Debug ]----------"
	@cd "rainflow_algorithm_v_0_2" && "$(MAKE)" -f  "rainflow_algorithm_v_0_2.mk"
clean:
	@echo "----------Cleaning project:[ rainflow_algorithm_v_0_2 - Debug ]----------"
	@cd "rainflow_algorithm_v_0_2" && "$(MAKE)" -f  "rainflow_algorithm_v_0_2.mk" clean
